### ISSUE TITLE
drawing a wireframe cube in WebGL not working

### ISSUE THREAD

**Issue by shiya** [greggman/webgl2-fundamentals#1]
Hey, on [this page](http://webgl2fundamentals.org/webgl/lessons/webgl-2d-vs-3d-library.html) the webGL demo is not working.

> webgl-utils.js:227 Uncaught TypeError: Cannot read property 'VERTEX_SHADER' of null

**Comment by greggman** [comment]
DOH! Thanks. I think it's fixed now. It should tell you you need to use Firefox or Chrome and enable WebGL2

**Comment by shiya** [comment]
Cool! I have WebGL2 enabled, it's showing up fine now 💃
