### ISSUE TITLE
Broken link on 'Text - Textures'

### ISSUE THREAD

**Issue by Scruffy1024** [greggman/webgl2-fundamentals#10]
In the 'Scaling Text without pixelation' section of 'Text - Using a Texture', the 'use very special shaders that render curves' link broke.
As far as I have seen, Microsoft is no longer hosting the file. I downloaded it before the link broke and have attached it here.
The same link is broken in the same place on webgl-fundamentals.
[CurveShaders.pdf](https://github.com/greggman/webgl2-fundamentals/files/923229/CurveShaders.pdf)

**Comment by greggman** [comment]
Thanks! I updated the link to a google search

https://github.com/greggman/webgl2-fundamentals/commit/8936d46af91c2d6f2db34e00344eae351eca7fa1
