### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by andrenoberto** [greggman/webgl2-fundamentals#16]
Hello, i'm a student of Computer Science at Rio Grande do Norte State University in Brazil.

I've been working on a translation to Brazilian Portuguese with a friend. We'd like to contribute to your repo translating the whole articles. I've made a fork and if you check my github you'll see that we've already started translating.

Thanks in advance.

**Comment by greggman** [comment]
That's awesome! Please make a pull request if you'd like to have your translation added to this repo

**Comment by andrenoberto** [comment]
Should I make a pull request regularly or just when I finish everything?

**Comment by greggman** [comment]
Regularly is probably better

**Comment by andrenoberto** [comment]
Okay, thanks for the answer.
