### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by fibo** [greggman/webgl2-fundamentals#2]
in page http://webgl2fundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html the **the WebGL Reference Card** which point to https://www.khronos.org/files/webgl/webgl-reference-card-2_0.pdf is broken.

Probably is this one, if yes I can do a PR to fix it: https://www.khronos.org/opengles/sdk/docs/reference_cards/OpenGL-ES-2_0-Reference-card.pdf

**Comment by greggman** [comment]
It's this one 

https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf

They haven't posted a 2.0 one yet :(   Maybe I should point to the ES 3.0 one until then

https://www.khronos.org/files/opengles3-quick-reference-card.pdf

or both

**Comment by fibo** [comment]
thanks, by the way the web site is great: it is the only resource I found with webgl2 documentation.

**Comment by greggman** [comment]
I'm going to close this as I update the links. I'll try to remember to update them again when the WebGL 2.0 reference sheet is out
