### ISSUE TITLE
missing positionBuffer definition

### ISSUE THREAD

**Issue by notdave22** [greggman/webgl2-fundamentals#41]
https://github.com/greggman/webgl2-fundamentals/blob/0338a8ede7b7d55cc43753eca208720c38b1c9e4/webgl/webgl-3d-lighting-point-specular.html#L143

add here 
`var positionBuffer = gl.createBuffer();`

**Comment by greggman** [comment]
fixed https://github.com/greggman/webgl2-fundamentals/commit/8cb42f4eb7c86db412570ae26212f945d139be74

ty
