### ISSUE TITLE
unelaborated webgl2 feature in the docs

### ISSUE THREAD

**Issue by jacobbogers** [greggman/webgl2-fundamentals#45]
in your documentation https://webgl2fundamentals.org/webgl/lessons/webgl-image-processing.html
states 

> WebGL2 adds the ability to read a texture using pixel coordinates as well. Which way is best is up to you. I feel like it's more common to use texture coordinates than pixel coordinates

what specific webgl2 added feature are you talking about?

**Comment by greggman** [comment]
It depends on what you're trying to do. For example if you're trying to generate a histogram or do some GPGPU thing then you probably want pixel coords

The feature is in GLSL using the `texelFetch` function. You give a sampler, integer pixel coordinates and a mip level

      vec4 color = texelFetch(someUniformSampler, ivec2(pixelX, pixelY), intMipLevel);

**Comment by jacobbogers** [comment]
Thanks greggman,  yes i am doing gpgpu (trying to implement multiplication of a banded matrix with a some other compatible matrix)
a bit of a segway,..., Does the GPU work backwards?? i mean in my mental model, the GPU first looks at the outputbuffer "output texture" (pixels it needs to draw eventually)... and then makes sure the _fragment shader_ code is called for every pixel to determine the "gl_FragColor" value to be set for the output texture.
This is how the gpu does parallelism (as i understand it so far). 

Is this correct?

is the texelFetch used in the vertext shader or fragment shader, I would love to see a minimal example where `texelFetch` is used. (maybe a simple histogram generation  you mentioned)

**Comment by greggman** [comment]
If you consider textures to be 2D arrays (or 3D arrays for 3D textures) then `texelFetch` lets you specifically address a single array element where that element contains up to 4 values (vec4, ivec4, uvec4, etc...). You can use texelFetch in either the vertex or fragment shaders.

The only sample on the site that uses texelFetch at the moment is [the skinning article](https://webgl2fundamentals.org/webgl/lessons/webgl-skinning.html)

It makes an array of 4 by N matrices in a texture and uses `texelFetch` to retrieve a matrix based on the index of the bone/joint for that matrix. You can compare it to the [WebGL1 skinning article](https://webglfundamentals.org/webgl/lessons/webgl-skinning.html). WebGL1 doesn't have `texelFetch` so there's a whole section saying how to compute normalized texture coordinates to achieve something similar.

Sorry but there's no really GPGPU articles yet.

You're correct that for the fragment shader the GPU is destination based. It figures out which pixels it needs to draw and then executes the fragment shader asking what color it should make that pixel.
