### ISSUE TITLE
your image example

### ISSUE THREAD

**Issue by jacobbogers** [greggman/webgl2-fundamentals#47]
previously you mentioned `gl_FragCoord` tracks the current to draw pixel coordinate (driven by the output canvas). 
what if the destination is not the canvas but a framebuffer (like in your picture filtering example).
will the gl_FragCoord contain the pixels of the output frame buffer?

Cheers

**Comment by greggman** [comment]
Yea, `gl_FragCoord` is always based on what is being drawn to. Also note that `gl_FragCoord` is not an integer.  WebGL measures pixels/texels by their edges. so

     0.0         1.0
      |           |
      V           V
      +-----+-----+
      |     |     | 
      +-----+-----+

If you were rendering to a 2x1 pixel framebuffer or canvas then when drawing the first pixel `gl_FragCoord` would be 0.25, 0.5 and for the second pixel it would be 0.75, 0.5

**Comment by jacobbogers** [comment]
Ah so I need to typecast back to int i.e  `int(gl_FragCoord.x)` 
lets say i dont want certain pixels to be rendered in the  output frame buffer, can i apply a mask of some sort? is that was [`gl.scissor`][https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/scissor] is for?  can I compose a non rectangular mask by calling scissors multiple times?

I could do something in the fragment shader based on `gl_FragCoord` of course.

just a spit-ball , can i apply another image/texture as lets say like a mask letting  the gl_FragCoord skip certain pixels based on the masking Texture?

Cheers
Jacob

**Comment by greggman** [comment]
You can `discard` based on whatever you want

```
   if (some expression) {
      discard; // don't write a pixel 
   }
```

**Comment by jacobbogers** [comment]
Given ( a bit of pseudo code) 
```javascript
 gl.texImage2D(
  gl.TEXTURE_2D, 
  mipLevel,
  internalFormat = gl.R8 ,
  image.width,
  image.height, 
  border =0,
  srcFormat = gl.R8,
  srcType= gl.UNSIGNED_BYTE, 
  data = Uint8ClampedArray
);
```
The data represents a 2D texture matrix, is it row first or column first?

**Comment by jacobbogers** [comment]
Hi, your sample doesnt work if i change it to webgl2, why is that?

I added `#version 300 es` to both shaders and `getContext('webgl2')`

http://jsfiddle.net/jacobot/vtx3af64

**Comment by greggman** [comment]
The syntax for GLSL changes in `#version 300 es`

https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html
