### ISSUE TITLE
Regarding multiple samplers

### ISSUE THREAD

**Issue by ivanpopelyshev** [greggman/webgl2-fundamentals#50]
Regarding https://github.com/greggman/webgl2-fundamentals/blob/master/webgl/lessons/webgl2-whats-new.md#samplers .

That's the case: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GraphicsBitmapFill.html

I thought that across the project with thousand swf files made by 10-20 artists in 7 years there wont be a case when they used different params on the same texture nearby and that i can choose one of them. I was wrong.

That's not the only interesting case there, I wrote them down and I'll make an article about it when I finish it.

**Comment by greggman** [comment]
I removed my comment from the article
