### ISSUE TITLE
Clarify sampler array indexing

### ISSUE THREAD

**Issue by kenrussell** [greggman/webgl2-fundamentals#9]
Thanks Gregg for putting together WebGL2Fundamentals. It's a great overview.

Unfortunately there's one small but significant bug. In WebGL 1.0 it was *optional* whether indexing of sampler arrays with variables was supported. Shaders using this feature might compile, or might not, depending on the capabilities of the underlying hardware.

The GLSL ES 3.00 specification forbids indexing of sampler arrays with anything except a constant. See sections 12.29 "Samplers" and 12.30 "Dynamic indexing".

We're looking into adding a WebGL 2.0 extension adding this functionality back in a guaranteed manner.

**Comment by greggman** [comment]
Thanks Ken. 

I removed that part here 857b25168b676cc885e8dfe29131a8f6a4ed0db9

**Comment by kenrussell** [comment]
Thanks Gregg!
